import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Observability',
      link: {
        type: 'generated-index',
        title: 'Observability',
        description: 'Enterprise-grade observability practices: distributed tracing, metrics collection, log aggregation, and the OpenTelemetry ecosystem.',
        slug: '/observability',
      },
      items: [
        'observability/introduction',
        'observability/three-pillars',
        'observability/logging',
        'observability/metrics',
        'observability/tracing',
        'observability/alerting',
        'observability/opentelemetry',
        {
          type: 'category',
          label: 'Language Integrations',
          link: {
            type: 'doc',
            id: 'observability/integrations/overview',
          },
          items: [
            'observability/integrations/go',
            'observability/integrations/dotnet',
            'observability/integrations/nodejs',
            'observability/integrations/python',
            'observability/integrations/java',
          ],
        },
        'observability/glossary',
      ],
    },
    {
      type: 'category',
      label: 'CI/CD',
      link: {
        type: 'generated-index',
        title: 'CI/CD',
        description: 'Complete CI/CD guide from foundations to enterprise patterns: pipeline design, deployment strategies, security, GitOps, and platform-specific implementations.',
        slug: '/cicd',
      },
      items: [
        'cicd/introduction',
        'cicd/core-concepts',
        'cicd/branching-strategies',
        'cicd/versioning-releases',
        'cicd/testing-quality',
        'cicd/artifact-management',
        'cicd/security-compliance-secrets',
        'cicd/deployment-strategies',
        'cicd/kubernetes-gitops',
        'cicd/platform-examples',
        'cicd/metrics-maturity',
        'cicd/pipeline-optimization',
        'cicd/troubleshooting',
        'cicd/ai-in-cicd',
        'cicd/enterprise-cicd',
        'cicd/anti-patterns-migration',
        'cicd/case-studies',
        'cicd/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Design Patterns',
      link: {
        type: 'generated-index',
        title: 'Design Patterns',
        description: 'A practical, end-to-end guide to design patterns with real-world context, multi-language implementations, and decision frameworks.',
        slug: '/design-patterns',
      },
      items: [{type: 'autogenerated', dirName: 'design-patterns'}],
    },
    {
      type: 'category',
      label: 'Best Practices',
      link: {
        type: 'generated-index',
        title: 'Best Practices',
        description: 'Code review guidelines, testing strategies, and documentation standards.',
        slug: '/best-practices',
      },
      items: [
        'best-practices/code-review',
        'best-practices/testing-strategies',
        'best-practices/documentation',
      ],
    },
    {
      type: 'category',
      label: 'Interview Guide',
      link: {
        type: 'doc',
        id: 'interview-guide/introduction',
      },
      items: [{type: 'autogenerated', dirName: 'interview-guide'}],
    },
  ],
};

export default sidebars;
